### ISSUE TITLE
Diskusijos

### ISSUE THREAD

**Issue by erkexzcx** [erkexzcx/tobot#7]
Yra kas naudojasi? Parasykit i komentarus :D

**Comment by SvarbusZodis** [comment]
Maybe Tutorial kaip pajunkti ant windows 10

**Comment by erkexzcx** [comment]
Veikia tik ant Linux. Naudok WSL'a arba VirtualBox.

**Comment by SvarbusZodis** [comment]
Dekui uz info

**Comment by SvarbusZodis** [comment]
any idea kodel neisiraso 
![image](https://user-images.githubusercontent.com/72148172/164965401-a599c635-8f37-4312-8687-eceed79f7833.png)

ant debian 9 
![image](https://user-images.githubusercontent.com/72148172/164965415-d2c6a83f-1968-4f11-9a81-427895853dc2.png)

**Comment by erkexzcx** [comment]
Pamegink pasiupdatint OS. Gal repos outdated:
```
apt update
apt upgrade
reboot
```

Ir tada po rebooto:
```
apt install tesseract-ocr tesseract-ocr-lit libtesseract-dev gcc g++ git
```

**Comment by SvarbusZodis** [comment]
dekui pamirsau updatint

**Comment by SvarbusZodis** [comment]
Dabar atsiranda problema vedant sia komanda ``go build -ldflags="-s -w" -o tobot ./cmd/tobot/main.go`` 
![image](https://user-images.githubusercontent.com/72148172/164965917-66d6ac0b-874d-456a-be64-9277012dd38c.png)

**Comment by erkexzcx** [comment]
Hmm, idomu. Kernel headers (kazkas panasaus i `linux-headers`) package isirases? Lyg ir turetu buti dependency kartu su `gcc` isirases.

**Comment by SvarbusZodis** [comment]
viskas yra irasyta
ka tik patikrinau

**Comment by erkexzcx** [comment]
Golang irgi naujausias? Isirasei is web'o, ne is official repos? `go version go1.18.1 linux/amd64`

**Comment by SvarbusZodis** [comment]
ai

**Comment by SvarbusZodis** [comment]
nera naujaujausias
isirasiau 1.17.1

**Comment by SvarbusZodis** [comment]
tuoj persirasysiu tada

**Comment by erkexzcx** [comment]
Docker containeryje pameginau subuildinti - irgi ta pati gaunu. Tuoj sugalvosiu kaip pafixinti.

**Comment by erkexzcx** [comment]
Sita prasuk ir veiks build komanda:
```
apt install libleptonica-dev
```

Paupdatinsiu wiki - anksciau nereikejo sito package.

**Comment by SvarbusZodis** [comment]
Okay viskas veikia bet norint paleisti bot gauni toki dalyka viskas config supildyta 
![image](https://user-images.githubusercontent.com/72148172/164966647-62a25610-dd19-4d81-9711-517c41b70000.png)

**Comment by erkexzcx** [comment]
Jo, tau raso kodel neveikia. Neranda modulio pavadinimu `food`. Paskaityk dokumentacija.

https://github.com/erkexzcx/tobot/wiki/Configuration#activities

**Comment by erkexzcx** [comment]
Va cia new playeriui skirti activities. Paziek reikalavimai.txt ir susidek viska ko reikia i inventoriu. Paleisk naudodamas sita folder ir viskas veiks. :)

https://github.com/erkexzcx/tobot/tree/master/activities/day1

**Comment by SvarbusZodis** [comment]
visus as jau rekalavimus turiu ir kaip suprast ``paleisti sita folderi``

**Comment by SvarbusZodis** [comment]
commands jeigu nesunku galetum numest

**Comment by erkexzcx** [comment]
> Okay viskas veikia bet norint paleisti bot gauni toki dalyka viskas config supildyta ![image](https://user-images.githubusercontent.com/72148172/164966647-62a25610-dd19-4d81-9711-517c41b70000.png)

Kazka praleidau. Gali but, kad bug'as ir jei nenurodai `food` optiono - tau neveiks. https://github.com/erkexzcx/tobot/blob/master/module/eating/eating.go#L102-L104

Parodyk savo activity yaml kuris sita error ismeta. Ar tu tiesiog naudoji `./activities/day1` ir tau meta?

> visus as jau rekalavimus turiu ir kaip suprast `paleisti sita folderi`

Tai tiesiog, savo `config.yml` playeriui nurodai `activities_dir: ./activities/day1`

**Comment by erkexzcx** [comment]
Nevermind, tiesiog parodyk ka esi nurodes moduliui `eating`. :facepalm: Parodyk savo activity YAML faila/failus.

**Comment by SvarbusZodis** [comment]
![image](https://user-images.githubusercontent.com/72148172/164968496-df667880-e0c8-4845-a958-b1d2158fd585.png)

**Comment by SvarbusZodis** [comment]
cia ss yra is config.yml

**Comment by SvarbusZodis** [comment]
> Nevermind, tiesiog parodyk ka esi nurodes moduliui `eating`. 🤦 Parodyk savo activity YAML faila/failus.

![image](https://user-images.githubusercontent.com/72148172/164968705-72371578-b060-4e3c-8552-e41afcf47f46.png)

**Comment by erkexzcx** [comment]
Butent taip ir atrodo pas tave?
```yaml
  - _module: eating
    food: UO1
```

Nes error'as sako, kad neatpazista tavo nurodyto `food` reiksmes.

Arba belenka nurodei, ko tob.lt zaidime nera, arba tob.lt turejo pokyciu kuriu nera siame projekte.

Va kokie galimi maistai, kuriuos gali valgyti: https://github.com/erkexzcx/tobot/blob/master/module/eating/eating.go#L16-L82

**Comment by erkexzcx** [comment]
Dar sako tau `slayer kelimas` activity - cia ir ieskok. Paziurek savo error'o screenshota.

**Comment by erkexzcx** [comment]
Greiciausiai kazka blogo nurodei `10_kovojimas.yml` faile. :)

**Comment by SvarbusZodis** [comment]
tuoj paziuresiu

**Comment by SvarbusZodis** [comment]
> Butent taip ir atrodo pas tave?
> 
> ```yaml
>   - _module: eating
>     food: UO1
> ```
> 
> Nes error'as sako, kad neatpazista tavo nurodyto `food` reiksmes.
> 
> Arba belenka nurodei, ko tob.lt zaidime nera, arba tob.lt turejo pokyciu kuriu nera siame projekte.
> 
> Va kokie galimi maistai, kuriuos gali valgyti: https://github.com/erkexzcx/tobot/blob/master/module/eating/eating.go#L16-L82

as viskas default palikau tai

**Comment by erkexzcx** [comment]
Identiskai atrodo? Ar kazka pakeitei? :)

https://github.com/erkexzcx/tobot/blob/master/activities/day1/10_kovojimas.yml#L4-L14

**Comment by SvarbusZodis** [comment]
> Identiskai atrodo? Ar kazka pakeitei? :)
> 
> https://github.com/erkexzcx/tobot/blob/master/activities/day1/10_kovojimas.yml#L4-L14

visiskai nekeiciau nieko ka pasikeiciau loginus ir telegram ir daugiau nekisau daugiau niekur nosies

**Comment by SvarbusZodis** [comment]
ir pas mane taip atrodo 
![image](https://user-images.githubusercontent.com/72148172/164968897-b67b0532-b5d2-44c2-9fc6-124ddf546ae7.png)

**Comment by erkexzcx** [comment]
jo, cia bug is manes. :facepalm: tuoj pafixinsiu.

**Comment by SvarbusZodis** [comment]
kai sutvarkysi parasysi

**Comment by erkexzcx** [comment]
Done:
```
git pull
go build -ldflags="-s -w" -o tobot ./cmd/tobot/main.go
```

**Comment by erkexzcx** [comment]
Beje, pasiupdatink config'e `min_rtt` value.

Pvz mano atveju:
```
ping tob.lt
PING tob.lt (194.135.91.53) 56(84) bytes of data.
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=1 ttl=58 time=59.2 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=2 ttl=58 time=59.5 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=3 ttl=58 time=325 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=4 ttl=58 time=1481 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=5 ttl=58 time=1667 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=6 ttl=58 time=58.8 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=7 ttl=58 time=2846 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=8 ttl=58 time=1816 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=9 ttl=58 time=792 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=10 ttl=58 time=58.3 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=11 ttl=58 time=59.2 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=12 ttl=58 time=60.4 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=13 ttl=58 time=62.7 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=14 ttl=58 time=60.3 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=15 ttl=58 time=59.3 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=16 ttl=58 time=59.5 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=17 ttl=58 time=59.0 ms
64 bytes from 286658.s.dedikuoti.lt (194.135.91.53): icmp_seq=18 ttl=58 time=59.0 ms
^C
--- tob.lt ping statistics ---
18 packets transmitted, 18 received, 0% packet loss, time 17720ms
rtt min/avg/max/mdev = 58.309/535.706/2845.808/815.809 ms, pipe 3
```

Min RTT yra `58.309` = `58ms`, todel pasidariau:
```
  min_rtt: 58ms
```


Mano full config kuri ka tik patestavau:
```yaml
telegram:
  api_key: XXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  chat_id: XXXXXXXX

settings:
  root_address: http://tob.lt
  user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
  min_rtt: 58ms
  become_offline:
    enabled: false
    every: 1h,2h
    for: 30m,60m
  randomize_wait:
    enabled: false
    wait_val: 0ms,4000ms

players:
  - nick: tobottest
    pass: OTI4MzVlYzdkYWExMDg2a3cfb871b2631a729190e19879fcf465 # tobottest
    activities_dir: ./activities/day1
```

**Comment by SvarbusZodis** [comment]
any ideas after reboot visada nebe veikia go commands
![image](https://user-images.githubusercontent.com/72148172/164970246-b67bc58d-2037-4355-a702-f0b1c9feaf48.png)

**Comment by SvarbusZodis** [comment]
![image](https://user-images.githubusercontent.com/72148172/164970474-e9b2aa9f-1e4d-425b-ad1a-2618a99b9146.png)
slaptazodis tinka viskas bet kiek skaiciau kad tipo slaptazodis neteisingas

**Comment by erkexzcx** [comment]
> any ideas after reboot visada nebe veikia go commands

Nes nepridedi i `$PATH` automatiskai. Pridek `export PATH=$PATH:/usr/local/go/bin` i `/root/.bashrc` ir logoff/login padaryk. Vel prisijunges jau turesi `go` komanda.

> slaptazodis tinka viskas bet kiek skaiciau kad tipo slaptazodis neteisingas

Taip, tau butent taip ir raso, kad slaptazodis neteisingas.

**Comment by SvarbusZodis** [comment]
bet slaptazodis yra teisingas ka tik net patikrinau

**Comment by erkexzcx** [comment]
Slaptazodi vedi savo, su kuriuo prisijungi prie tob.lt? Ar is URL paemei?

Skaitei cia? https://github.com/erkexzcx/tobot/wiki/Configuration yra komentarai sudeti su pavyzdziais.

**Comment by SvarbusZodis** [comment]
tiesiog vedu password ne url
